import * as abis from 'abi/generated';

/**
 * Maps contract names (as they appear in contract-addresses.ts) to their ABI
 * when the name doesn't directly match the generated ABI key, or when the
 * contract shares an ABI with a differently-named contract.
 */
export const ABI_EXCEPTIONS = {
  StETH: abis.stethAbi,
  HashConsensusAccountingOracle: abis.hashConsensusAbi,
  HashConsensusValidatorsExitBus: abis.hashConsensusAbi,
  CuratedHashConsensus: abis.hashConsensusAbi,
  LidoAppRepo: abis.repoAbi,
  NodeOperatorsRegistryRepo: abis.repoAbi,
  OracleRepo: abis.repoAbi,
  SimpleDVTNodeOperatorsRegistry: abis.nodeOperatorsRegistryAbi,
  CuratedV1NodeOperatorsRegistry: abis.nodeOperatorsRegistryAbi,
  WithdrawalQueue: abis.withdrawalQueueErc721Abi,
  DualGovernanceLegacy: abis.dualGovernanceAbi,
  AllowedRecipientRegistry: abis.allowedRecipientsRegistryAbi,
  AllowedRecipientReferralDaiRegistry: abis.allowedRecipientsRegistryAbi,
  AllowedRecipientTrpLdoRegistry: abis.allowedRecipientsRegistryAbi,
  StethRewardProgramRegistry: abis.allowedRecipientsRegistryAbi,
  StethGasSupplyRegistry: abis.allowedRecipientsRegistryAbi,
  RewardsShareProgramRegistry: abis.allowedRecipientsRegistryAbi,
  SandboxAllowedRecipientsRegistry: abis.registryWithLimitsAbi,
  LegoStablesRegistry: abis.registryWithLimitsAbi,
  LegoLDORegistry: abis.registryWithLimitsAbi,
  GasFunderETHRegistry: abis.registryWithLimitsAbi,
  RccStablesRegistry: abis.registryWithLimitsAbi,
  PmlStablesRegistry: abis.registryWithLimitsAbi,
  AtcStablesRegistry: abis.registryWithLimitsAbi,
  SandboxStablesAllowedRecipientRegistry: abis.registryWithLimitsAbi,
  RccStethAllowedRecipientsRegistry: abis.registryWithLimitsAbi,
  PmlStethAllowedRecipientsRegistry: abis.registryWithLimitsAbi,
  AtcStethAllowedRecipientsRegistry: abis.registryWithLimitsAbi,
  StonksStethAllowedRecipientsRegistry: abis.registryWithLimitsAbi,
  StonksStablesAllowedRecipientsRegistry: abis.registryWithLimitsAbi,
  LOLStablecoinsAllowedRecipientsRegistry: abis.registryWithLimitsAbi,
  LOLLDOAllowedRecipientsRegistry: abis.registryWithLimitsAbi,
  AllianceOpsAllowedRecipientsRegistry: abis.registryWithLimitsAbi,
  EcosystemOpsStablesAllowedRecipientsRegistry: abis.registryWithLimitsAbi,
  LabsOpsStablesAllowedRecipientsRegistry: abis.registryWithLimitsAbi,
  EcosystemOpsStethAllowedRecipientsRegistry: abis.registryWithLimitsAbi,
  LabsOpsStethAllowedRecipientsRegistry: abis.registryWithLimitsAbi,
  BurnerLegacy: abis.burnerAbi,
  OracleReportSanityCheckerLegacy: abis.oracleReportSanityCheckerV2Abi,
  DepositSecurityModuleLegacy: abis.depositSecurityModuleAbi,
  CSVerifierLegacy: abis.csVerifierAbi,
  CSEjectorLegacy: abis.csEjectorAbi,
  DAI: abis.erc20Abi,
  USDC: abis.erc20Abi,
  USDT: abis.erc20Abi,
  LDOToken: abis.miniMeTokenAbi,
  SandboxNodeOperatorsRegistry: abis.nodeOperatorsRegistryAbi,
  SimpleDVTRepo: abis.repoAbi,
  DualGovernanceResealManager: abis.resealManagerAbi,
  VetoSignalingEscrow: abis.dgEscrowAbi,
  DualGovernanceConfigProvider: abis.dgConfigProviderAbi,
  ReserveFund: abis.insuranceFundAbi,
  CSModule: abis.csmRegistryAbi,
  CoreAccounting: abis.accountingAbi,
  CSMParametersRegistry: abis.parametersRegistryAbi,
  CSMExitPenalties: abis.exitPenaltiesAbi,
  CSMValidatorStrikes: abis.validatorStrikesAbi,
  CuratedMetaRegistry: abis.metaRegistryAbi,
  CSMVettedCommunityStakersGate: abis.csmVettedGateAbi,
  CSMVettedDVTGate: abis.csmVettedGateAbi,
  CuratedAccounting: abis.accountingAbi,
  CuratedFeeOracle: abis.csFeeOracleAbi,
  CuratedVerifier: abis.csVerifierAbi,
  CuratedEjector: abis.csEjectorAbi,
} as const;

export type AbiExceptionContractName = keyof typeof ABI_EXCEPTIONS;
