export const NAV_MOBILE_HEIGHT = 60;
export const NAV_TABLET_MAX_WIDTH = 1100;
export const NAV_MOBILE_MAX_WIDTH = 640;
export const VOTE_MOBILE_MAX_WIDTH = 999;
export const VOTE_CARD_MAX_WIDTH = 1024;
export const VOTE_CARD_MOBILE_MAX_WIDTH = 560;
export const VOTE_CARD_FULL_BLEED_MAX_WIDTH = 599;
